### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by layasamadhi** [tkojima0107/popclip2notion#1]
This is the message error:

<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>

**Comment by tkojima0107** [comment]
I can't say for sure but it seems an issue in Python3 like https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error.
If you tell me more detailed information (e.g., versions of macOS, python3, etc), I might be able to help you.
As far as I tested on my Mac (macOS 11.4 with Python 3.8 from Xcode), that error does not occur.

**Comment by layasamadhi** [comment]
MacOS 12.2 and Python 3.10.2. I'm not developer, therefore my skills are limited.

**Comment by tkojima0107** [comment]
You might have installed python3 by using an installer released from https://www.python.org/downloads/release/python-3102 instead of Command Line Tool from Apple.
If true, I guess a few steps for instaling Python3 remain.
The following steps cloud fix your problem.
1. Open Finder
2. Click "Go" -> "Applications" in the menu bar.
3. You will see "Python 3.10" folder so please open this folder.
4. It will contains "Install Certificates.command" like the figure below.
5. Double click "Install Certificates.commnad"
Then, some package installation will start automatically.
<img width="674" alt="image" src="https://user-images.githubusercontent.com/32124639/151561226-e200b908-757c-4b13-b9d2-1f051d41e334.png">

**Comment by layasamadhi** [comment]
Done. Now the error is this:
"HTTP error 404. Not found"

<img width="168" alt="CleanShot 2022-01-28 at 17 51 42@2x" src="https://user-images.githubusercontent.com/6170216/151588183-c08bae2e-9a19-49f9-92de-c346540c57a6.png">

**Comment by tkojima0107** [comment]
Did you invite your integration to a page you want to send a text as Step 2 in https://developers.notion.com/docs/getting-started ?

**Comment by layasamadhi** [comment]
I redid everything from scratch: page and integration. Now works, great extension. Thank you very much.
